version: '3.8'

services:
  backend:
    container_name: referral-system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6.0
    container_name: referral-mongo
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
